config/routes.rb
Rails.application.routes.draw do
  get 'events/index'

  get 'event/index'

  get 'welcome/index'

  root 'welcome#index'

  resources :articles do
		resources :comments
	end

  resources :events do
    member do
      get 'upload_auctions'
      get 'upload_guests'
    end
    resources :auctions
    resources :guests
    resources :bid_numbers
  end

  resources :guests
  
  resources :auctions do
    resources :bids
  end

  resources :bid_numbers do
    resources :invoices 
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments
	validates	:title, presence: true,
						length: {minimum: 5}
end

app/models/auction.rb
class Auction < ActiveRecord::Base
	belongs_to :event
	has_many :bids, :dependent => :destroy

	validates	:name, presence: true, uniqueness: true, length: {maximum: 80}
end

app/models/bid.rb
class Bid < ActiveRecord::Base
	belongs_to :auction
end

app/models/bid_number.rb
class BidNumber < ActiveRecord::Base
	belongs_to :event
	has_many :invoices, :dependent => :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :auctions, :dependent => :destroy
	has_many :guests, :dependent => :destroy
	has_many :bid_numbers, :dependent => :destroy
end

app/models/guest.rb
class Guest < ActiveRecord::Base
	belongs_to :event

	validates	:first_name, presence: true, length: {maximum: 80}
	validates	:last_name, presence: true, length: {maximum: 80}
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
	belongs_to :bid_number
	has_many :invoice_entries , dependent: :destroy
	
end

app/models/invoice_entry.rb
class InvoiceEntry < ActiveRecord::Base
	belongs_to :invoice
	
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController


	def destroy
	    @auction = Auction.find(params[:auction_id])
	    if(@auction.status == "OPEN")
		    @bid = @auction.bids.find(params[:id])
		    @bid.destroy
		    redirect_to auction_path(@auction), notice: "Bid is successfully deleted!"
		else
			redirect_to auction_path(@auction), notice: "Reopen the auction!"
		end

  	end
  	
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController

  def index
    @event = Event.find(params[:event_id])
	  @guests = Guest.where(event_id: params[:event_id]).order(:guest_of)
  end

  def new
    @event = Event.find(params[:event_id])
	  @guest = @event.guests.build
  end

  def edit
    @guest = Guest.find(params[:id])
    @event = Event.find(@guest.event_id)
  end


  def create
    @event = Event.find(params[:event_id])
    @guest = @event.guests.create(guest_params)

    # Create bid number in system if not already present
  	bid_number = @guest.bid_number

    save_bid_num_result = true
    save_guest_result = true
    
    Guest.transaction do
      if !bid_number.blank?
        @bid_number_ob = BidNumber.where(bid_number: bid_number).first
        if !@bid_number_ob
          @bid_number_ob = @event.bid_numbers.create(:bid_number => bid_number, :event_due_amount => 0, :event_due_pay_status => "UNPAID", :invoice_email_status => "NOT_SENT")
          save_bid_num_result = @bid_number_ob.save
        end
      end
      save_guest_result = @guest.save
    end # end of transaction
    
    if save_bid_num_result && save_guest_result
      redirect_to  guest_path(@guest), notice: "Guest saved"
    else
      render 'edit'
    end
  end

  def update
    @guest = Guest.find(params[:id])
    @event = Event.find(@guest.event_id)
    
    # Create bid number in system if not already present
    bid_number = params[:guest][:bid_number]
    save_bid_num_result = true
    update_guest_result = true

    Guest.transaction do
      if !bid_number.blank?
        @bid_number_ob = BidNumber.where(bid_number: bid_number).first
        if !@bid_number_ob
          @bid_number_ob = @event.bid_numbers.create(:bid_number => bid_number, :event_due_amount => 0, :event_due_pay_status => "NOT_PAID", :invoice_email_status => "NOT_SENT")
          save_bid_num_result = @bid_number_ob.save
        end
      end
      update_guest_result = @guest.update(guest_params)
      @guest.update_attributes(event_status: "ARRIVED")
      @guest.save
    end # end of transaction

    if save_bid_num_result && update_guest_result
      redirect_to  guest_path(@guest), notice: "Guest updated"
    else
      render 'edit'
    end
  end

  def show
    @guest = Guest.find(params[:id])
    @event = Event.find(@guest.event_id)
  end

  def destroy
    @guest = Guest.find(params[:id])
    @guest.destroy
    redirect_to guests_path(@event), notice: "Guest is successfully deleted!"
  end

 private
  def guest_params
    params.require(:guest).permit(:first_name, :last_name, :middle_name, :guest_of,:billing_address_1, :billing_address_2, :city, :state, :zip_code,:email, :phone_number, :bid_number, :table_number, :dinner_tickets, :registration_status, :registration_fee, :registration_fee_mode, :event_status, :fee_adjustment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def get_guests_with_bid_number(bid_number)
		return Guest.where(bid_number: bid_number)
	end
	def get_guests_name_by_guest_id(guest_id)
		host = Guest.find(guest_id)
		return host.first_name + " " + host.last_name
	end

	def get_auction_type_heading(auction_type)
		case auction_type
		when "FUND_A_NEED"
			"Fund A Need"
		when "SILENT_AUCTION"
			"Item Purchase"
		when "MERCHANDISE"
			"Merchandise"
		when "DESSERT_DASH"
			"Dessert Dash"
		else
			"NOT KNOWN"
		end
	end

	def get_auction_by_id(auction_id)
		return Auction.find(auction_id)
	end

	def get_donation_by_guest_id(guest_id)
		return Auction.where(donor_id: guest_id).reorder('name')
	end

	def get_invoice_entries_by_auction_type(invoice_id)
		invoice_entries_by_auction_type_hash = Hash.new {|h,atype| h[atype]=[]}
		result_ies = InvoiceEntry.where(invoice_id: invoice_id).reorder('auction_type')
		result_ies.each do |result_ie|
			invoice_entries_by_auction_type_hash[result_ie.auction_type] << result_ie
		end
		return invoice_entries_by_auction_type_hash
	end

	def float_or_zero(amount)
		if amount.blank?
		 return Float(0)
		end
		Float(amount)
	rescue ArgumentError
		Float(0)
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper

	def guests_for_donor_select
		Guest.all.collect {|m| [m.first_name + " " + m.last_name, m.id]} 
	end

	def guest_name_by_id(guest_id)
		guest = Guest.find(guest_id)
		if !guest.blank?
			guest.first_name + " " +guest.last_name
		else
			return ""
		end
	end

	def guest_name_by_bid_number(bid_number)
		guest = Guest.where(bid_number: bid_number)
		if !guest.blank? 
			guest.first_name + " " +guest.last_name
		else
			return ""
		end
	end
end

app/helpers/bid_numbers_helper.rb
module BidNumbersHelper

end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/guests_helper.rb
module GuestsHelper

	def guests_of_event(event)
		Guest.where(event_id: event.id).collect {|m| [m.first_name + " " + m.last_name, m.id]} 
	end

	def get_bid_number_by_number_value(bid_number)
		if bid_number.blank?
			return nil
		else 
			BidNumber.where(bid_number: bid_number).first
		end
	end

	def get_guests_by_bid_number(bid_number)
		return Guest.where(bid_number: bid_number)
	end
end

app/helpers/invoices_helper.rb
module InvoicesHelper


end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/guests/_form.html.erb
<%= form_for ([@event, @guest]),:html => {:class => "form-horizontal center"} do |f|%>

	<% if @guest && @guest.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@guest.errors.count, "error") %> prohibited this guest from being saved:
			</h2>
			<ul>
				<% @guest.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="form-group">
			<%= f.label :first_name, class: "col-md-4 control-label"%>
			<div class="col-md-8">
			<%= f.text_field :first_name %>
			</div>
	</div>
	<div class="form-group">
		<%= f.label :middle_name, class: "col-md-4 control-label"%>
		<div class="col-md-8">
		<%= f.text_field :middle_name %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :last_name, class: "col-md-4 control-label"%>
		<div class="col-md-8">
		<%= f.text_field :last_name %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :guest_of, class: "col-md-4 control-label"%>
		<div class="col-md-8">
		<%= f.text_field :guest_of %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :billing_address_1, class: "col-md-4 control-label"%>
		<div class="col-md-8">
		<%= f.text_field :billing_address_1 %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :billing_address_2, class: "col-md-4 control-label"%>
		<div class="col-md-8">
		<%= f.text_field :billing_address_2 %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :city, class: "col-md-4 control-label"%>
		<div class="col-md-8">
		<%= f.text_field :city %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :state, class: "col-md-4 control-label"%>
		<div class="col-md-8">
		<%= f.text_field :state %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :zip_code, class: "col-md-4 control-label"%>
		<div class="col-md-8">
		<%= f.text_field :zip_code %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :email, class: "col-md-4 control-label"%>
		<div class="col-md-8">
		<%= f.text_field :email %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :phone_number, class: "col-md-4 control-label"%>
		<div class="col-md-8">
		<%= f.text_field :phone_number %>
		</div>
	</div>
		<div class="form-group">
		<%= f.label :bid_number, class: "col-md-4 control-label"%>
		<div class="col-md-8">
		<%= f.text_field :bid_number %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :dinner_tickets, class: "col-md-4 control-label"%>
		<div class="col-md-8">
		<%= f.text_field :dinner_tickets %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :table_number, class: "col-md-4 control-label"%>
		<div class="col-md-8">
		<%= f.text_field :table_number %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :registration_fee, class: "col-md-4 control-label"%>
		<div class="col-md-8">
		<%= f.text_field :registration_fee %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :registration_status, class: "col-md-4 control-label"%>
		<div class="col-md-8">
			<%= f.select(:registration_status) do %>
	 			 <% [['PAID','PAID'],['UNPAID','UNPAID'],['COMPED','COMPED']].each do |c| -%>
		 			 	<% if @guest && @guest.registration_status == c.first %>
		    		 		<%= content_tag(:option, c.first, value: c.last, selected: true) %>
		    		 	<% else %>
		    		 		<%= content_tag(:option, c.first, value: c.last) %>
		    		 	<% end %>
				 <% end %>
			<% end %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :registration_fee_mode, class: "col-md-4 control-label"%>
		<div class="col-md-8">
			<%= f.select(:registration_fee_mode) do %>
	 			 <% [['ONLINE','ONLINE'],['CASH','CASH'],['CHEQUE','CHEQUE']].each do |c| -%>
		 			 	<% if @guest && @guest.registration_fee_mode == c.first %>
		    		 		<%= content_tag(:option, c.first, value: c.last, selected: true) %>
		    		 	<% else %>
		    		 		<%= content_tag(:option, c.first, value: c.last) %>
		    		 	<% end %>
				 <% end %>
			<% end %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :event_status, class: "col-md-4 control-label"%>
		<div class="col-md-8">
			<%= f.select(:event_status) do %>
	 			 <% [['REGISTERED','REGISTERED'],['ARRIVED','ARRIVED'],['CHECKED_OUT','CHECKED_OUT']].each do |c| -%>
		 			 	<% if @guest && @guest.event_status == c.first %>
		    		 		<%= content_tag(:option, c.first, value: c.last, selected: true) %>
		    		 	<% else %>
		    		 		<%= content_tag(:option, c.first, value: c.last) %>
		    		 	<% end %>
				 <% end %>
			<% end %>
		</div>
	</div>

	<div class="form-group">
		<div class="col-md-8">
			<%= f.submit "Submit", class: "btn btn-default btn-primary"%>
		</div>
	</div>

<% end %>

app/views/guests/edit.html.erb
<div class="container-fluid">
	<%= render 'common/navbar' %>
</div>
<%= link_to 'Back', event_guests_path %>

<h1>Editing Guest</h1>

<%= render 'form' %>

app/views/guests/index.html.erb
<div class="container-fluid">
	<%= render 'common/navbar' %>
</div>
<%= link_to 'Back', event_path(@event) %>
<h1>Guests</h1>
<ul class="nav nav-pills" role="tablist">
	<li role="presentation" class="active">
		<%= link_to 'New Guest', new_event_guest_path , {:class => 'badge'}%>
	</li>
</ul>

<div class="table-responsive">
 <table class="table table-striped">
	<tr>
		<th>Guest Count</tn>
		<th>First Name</th>
		<th>Last Name</th>
		<th>Guest Of</th>
		<th>Email</th>
		<th>Phone Number</th>
		<th>Bid Number</th>
		<th>Dinner Tickets</th>
		<th>Registration Fee Amount</th>
		<th>Registration Fee Status</th>
		<th>Table Number</th>
		<th>Event Status</th>
		<th>Show</th><th>Edit</th><th>Delete</th>
	</tr>
	<% guest_count = 0 %>
	<% @guests.each do |guest| %>
	<% guest_count += 1%>
		<tr>
			<td><%= guest_count %></td>
			<td><%= guest.first_name %></td>
			<td><%= guest.last_name %></td>
			<td><%= guest.guest_of %></td>
			<td><%= guest.email %></td>
			<td><%= guest.phone_number %></td>
			<% bid_number_ob = get_bid_number_by_number_value(guest.bid_number) %>
			<% if bid_number_ob.blank? %>
				<td><%= guest.bid_number %></td>
			<% else %>
				<td><%= link_to guest.bid_number , [bid_number_ob.event, bid_number_ob] %></td>
			<% end %>
			<td><%= guest.dinner_tickets %></td>
			<td><%= guest.registration_fee%></td>
			<td><%= guest.registration_status%></td>
			<td><%= guest.table_number %></td>
			<td><%= guest.event_status%></td>
			<td><%= link_to 'Show' , [guest.event, guest] %></td>
			<td><%= link_to 'Edit' , edit_event_guest_path(guest.event, guest)%></td>
			<td><%= link_to 'Delete' , [guest.event, guest] , method: :delete, data: {confirm: 'Are you sure?' } %></td>
		</tr>
	<% end %>
</table>
</div>

app/views/guests/new.html.erb
<div class="container-fluid">
	<%= render 'common/navbar' %>
</div>

<h1> Create a new Guest</h1>

<%= render 'form' %>

<%= link_to 'Back', event_guests_path(@event) %>

app/views/guests/show.html.erb
<div class="container-fluid">
	<%= render 'common/navbar' %>
</div>
<p>
<%= link_to 'Back', event_guests_path(@event) %>
</p>
<div class="greenbgcolor">
    <% guests_with_bid_number = get_guests_by_bid_number(@guest.bid_number) %>  
      <% if guests_with_bid_number.size > 0 %>
      <p><strong>Guests with same Bid Number</strong></p>
      <% guests_with_bid_number.each do |guest_with_bid_number|%>
        <p> <%= guest_with_bid_number.first_name + "  " + guest_with_bid_number.last_name %></p>
      <% end %>
    <% end %>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3">
    <p>
      <strong>First Name:</strong>
    </p>
    <p>
      <strong>Middle Name:</strong>
    </p>
    <p>
      <strong>Last Name:</strong>
    </p>
    <p>
      <strong>Guest of:</strong>
    </p>
    <p>
      <strong>Billing Address Line1:</strong>
    </p>
    <p>
      <strong>Billing Address Line2:</strong>
    </p>
    <p>
      <strong>City:</strong>
    </p>
    <p>
      <strong>State:</strong>
    </p>
    <p>
      <strong>Zip Code:</strong>
    </p>
    <p>
      <strong>Email:</strong>
    </p>
    <p>
      <strong>Phone Number:</strong>
    </p>
    <p>
      <strong>Bid Number:</strong>
    </p>
    <p>
      <strong>Dinner Tickets:</strong>
    </p>
    <p>
      <strong>Registration Fee:</strong>
    </p>
    <p>
      <strong>Registration Fee Status:</strong>
    </p>
    <p>
      <strong>Table Number:</strong>
    </p>
    <p>
      <strong>Event Status:</strong>
    </p>
    <p>
    </div>
    <div class="col-sm-6">
      <p>:<%= @guest.first_name %></p>
      <p>:<%= @guest.middle_name %> </p>
      <p>:<%= @guest.last_name %> </p>
      <p>:<%= @guest.guest_of %> </p>
      <p>:<%= @guest.billing_address_1 %></p>
      <p>:<%= @guest.billing_address_2 %></p>
      <p>:<%= @guest.city %> </p>
      <p>:<%= @guest.state %> </p>
      <p>:<%= @guest.zip_code %> </p>
      <p>:<%= @guest.email %> </p>
      <p>:<%= @guest.phone_number%></p>
      <p>:<%= @guest.bid_number%></p>
      <p>:<%= @guest.dinner_tickets %></p>
      <p>:<%= @guest.registration_fee %> </p>
      <p>:<%= @guest.registration_status %> </p>
      <p>:<%= @guest.table_number %></p>
      <p>:<%= @guest.event_status %> </p>
    </div>
  </div>
</div>