config/routes.rb
Rails.application.routes.draw do
  get 'events/index'

  get 'event/index'

  get 'welcome/index'

  root 'welcome#index'

  resources :articles do
		resources :comments
	end

  resources :events do
    member do
      get 'upload_auctions'
      get 'upload_guests'
    end
    resources :auctions
    resources :guests
    resources :bid_numbers
  end

  resources :guests
  
  resources :auctions do
    resources :bids
  end

  resources :bid_numbers do
    resources :invoices 
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments
	validates	:title, presence: true,
						length: {minimum: 5}
end

app/models/auction.rb
class Auction < ActiveRecord::Base
	belongs_to :event
	has_many :bids, :dependent => :destroy

	validates	:name, presence: true, uniqueness: true, length: {maximum: 80}
end

app/models/bid.rb
class Bid < ActiveRecord::Base
	belongs_to :auction
end

app/models/bid_number.rb
class BidNumber < ActiveRecord::Base
	belongs_to :event
	has_many :invoices, :dependent => :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :auctions, :dependent => :destroy
	has_many :guests, :dependent => :destroy
	has_many :bid_numbers, :dependent => :destroy
end

app/models/guest.rb
class Guest < ActiveRecord::Base
	belongs_to :event

	validates	:first_name, presence: true, length: {maximum: 80}
	validates	:last_name, presence: true, length: {maximum: 80}
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
	belongs_to :bid_number
	has_many :invoice_entries , dependent: :destroy
	
end

app/models/invoice_entry.rb
class InvoiceEntry < ActiveRecord::Base
	belongs_to :invoice
	
end

app/controllers/bid_numbers_controller.rb
class BidNumbersController < ApplicationController

	def index
		@event = Event.find(params[:event_id])
		@bid_numbers = BidNumber.where(event_id: params[:event_id])
	end

	def new
		@event = Event.find(params[:event_id])
		@bid_number = @event.bid_numbers.build
	end


	def edit
    	@bid_number = BidNumber.find(params[:id])
    	@event = Event.find(@bid_number.event_id)
	end

	def show
    	@bid_number = BidNumber.find(params[:id])
    	@event = Event.find(@bid_number.event_id)
  	end

  	def update
	    @bid_number = BidNumber.find(params[:id])
 
	    if @bid_number.update(bid_number_params)
	      redirect_to @bid_number
	    else
	      render 'edit'
	    end
  	end

	def create
		@event = Event.find(params[:event_id])
		@bid_number = @event.bid_numbers.build(bid_number_params)
		@bid_number.event_due_amount = 0
		@bid_number.event_due_pay_status = "UNPAID"
		@bid_number.invoice_email_status = "NOT_SENT"
		@bid_number.save
		if @bid_number && @bid_number.errors.any? 
			render 'edit'
		else
			redirect_to event_bid_numbers_path(@event)
		end
	end

	def destroy
	    @event = Event.find(params[:event_id])
	    @bid_number = @event.bid_numbers.find(params[:id])
	    @guests = Guest.where(bid_number: @bid_number.bid_number)
	    if @guests.blank?
	    	@bid_number.destroy
	    end
	    redirect_to event_bid_numbers_path(@event), notice: "Bid number will be deleted if not assigned to a guest"
  	end

	private
	  def bid_number_params
	    params.require(:bid_number).permit(:bid_number, :fee_adjustment)
	  end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController


	def destroy
	    @auction = Auction.find(params[:auction_id])
	    if(@auction.status == "OPEN")
		    @bid = @auction.bids.find(params[:id])
		    @bid.destroy
		    redirect_to auction_path(@auction), notice: "Bid is successfully deleted!"
		else
			redirect_to auction_path(@auction), notice: "Reopen the auction!"
		end

  	end
  	
end

app/helpers/application_helper.rb
module ApplicationHelper

	def get_guests_with_bid_number(bid_number)
		return Guest.where(bid_number: bid_number)
	end
	def get_guests_name_by_guest_id(guest_id)
		host = Guest.find(guest_id)
		return host.first_name + " " + host.last_name
	end

	def get_auction_type_heading(auction_type)
		case auction_type
		when "FUND_A_NEED"
			"Fund A Need"
		when "SILENT_AUCTION"
			"Item Purchase"
		when "MERCHANDISE"
			"Merchandise"
		when "DESSERT_DASH"
			"Dessert Dash"
		else
			"NOT KNOWN"
		end
	end

	def get_auction_by_id(auction_id)
		return Auction.find(auction_id)
	end

	def get_donation_by_guest_id(guest_id)
		return Auction.where(donor_id: guest_id).reorder('name')
	end

	def get_invoice_entries_by_auction_type(invoice_id)
		invoice_entries_by_auction_type_hash = Hash.new {|h,atype| h[atype]=[]}
		result_ies = InvoiceEntry.where(invoice_id: invoice_id).reorder('auction_type')
		result_ies.each do |result_ie|
			invoice_entries_by_auction_type_hash[result_ie.auction_type] << result_ie
		end
		return invoice_entries_by_auction_type_hash
	end

	def float_or_zero(amount)
		if amount.blank?
		 return Float(0)
		end
		Float(amount)
	rescue ArgumentError
		Float(0)
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper

	def guests_for_donor_select
		Guest.all.collect {|m| [m.first_name + " " + m.last_name, m.id]} 
	end

	def guest_name_by_id(guest_id)
		guest = Guest.find(guest_id)
		if !guest.blank?
			guest.first_name + " " +guest.last_name
		else
			return ""
		end
	end

	def guest_name_by_bid_number(bid_number)
		guest = Guest.where(bid_number: bid_number)
		if !guest.blank? 
			guest.first_name + " " +guest.last_name
		else
			return ""
		end
	end
end

app/helpers/bid_numbers_helper.rb
module BidNumbersHelper

end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/guests_helper.rb
module GuestsHelper

	def guests_of_event(event)
		Guest.where(event_id: event.id).collect {|m| [m.first_name + " " + m.last_name, m.id]} 
	end

	def get_bid_number_by_number_value(bid_number)
		if bid_number.blank?
			return nil
		else 
			BidNumber.where(bid_number: bid_number).first
		end
	end

	def get_guests_by_bid_number(bid_number)
		return Guest.where(bid_number: bid_number)
	end
end

app/helpers/invoices_helper.rb
module InvoicesHelper


end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bid_numbers/_form.html.erb
<%= form_for ([@event, @bid_number]),:html => {:class => "form-horizontal center"} do |f|%>

	<% if @bid_number && @bid_number.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@bid_number.errors.count, "error") %> prohibited this bid_number from being saved:
			</h2>
			<ul>
				<% @bid_number.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="form-group">
		<%= f.label :bid_number, class: "col-md-4 control-label"%>
		<div class="col-md-8">
		<%= f.text_field :bid_number , size: 40 %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :fee_adjustment, class: "col-md-4 control-label"%>
		<div class="col-md-8">
		<%= f.text_field :fee_adjustment , size: 40 %>
		</div>
	</div>
	<div class="form-group">
		<div class="col-md-8">
			<%= f.submit "Submit", class: "btn btn-default btn-primary"%>
		</div>
	</div>
<% end %>

app/views/bid_numbers/edit.html.erb
<div class="container-fluid">
	<%= render 'common/navbar' %>
</div>

<h1>Editing Bid Number</h1>

<%= render 'form' %>

<%= link_to 'Back', event_bid_numbers_path %>

app/views/bid_numbers/index.html.erb
<div class="container-fluid">
	<%= render 'common/navbar' %>
</div>
<%= link_to 'Back', event_path(@event) %>
<h1>Bid Numbers</h1>

<ul class="nav nav-pills" role="tablist">
	<li role="presentation" class="active">
		<%= link_to 'New Bid Number', new_event_bid_number_path , {:class => 'badge'}%>
	</li>
</ul>


<div class="table-responsive">
 <table class="table table-striped">
	<tr>
		<th>Bid Number</th>
		<th>Event Due Amount</th>
		<th>Event Due Pay Status</th>
		<th>Invoice Email Status</th>
		<th>Fee Adjustment</th>
	</tr>
	<% @bid_numbers.each do |bid_number|  %>

		<tr>
			<td><%= bid_number.bid_number %></td>
			<td><%= bid_number.event_due_amount %></td>
			<td><%= bid_number.event_due_pay_status %></td>
			<td><%= bid_number.invoice_email_status %></td>
			<td><%= bid_number.fee_adjustment %></td>
			<td><%= link_to 'Show' , [bid_number.event, bid_number] %></td>
			<td><%= link_to 'Edit' , edit_event_bid_number_path(bid_number.event, bid_number)%></td>
			<td><%= link_to 'Delete' , [bid_number.event, bid_number] , method: :delete, data: {confirm: 'Are you sure?' } %></td>
		</tr>
		<% @guests = get_guests_with_bid_number(bid_number.bid_number) %>
		<% @guests.each do |guest| %>
			<tr><td><%= guest.first_name + " " +guest.last_name %></td>
			<td><%= link_to 'Show' , [guest.event, guest] %></td></tr>
		<% end %>
	<% end %>
</table>
</div>

app/views/bid_numbers/new.html.erb
<div class="container-fluid">
	<%= render 'common/navbar' %>
</div>

<h1> Create a new Bid Number</h1>

<%= render 'form' %>

<%= link_to 'Back', event_bid_numbers_path %>

app/views/bid_numbers/show.html.erb
<div class="container-fluid">
	<%= render 'common/navbar' %>
</div>

<p>
<%= link_to 'Back', event_bid_numbers_path(@event) %>
</p>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3">
      <p>
        <strong>Bid Number:</strong>
      </p>
      <p>
        <strong>Event Due Amount:</strong>
      </p>
      <p>
        <strong>Event Due Pay Status:</strong>
      </p>
      <p>
        <strong>Invoice Email Status:</strong>
      </p>
      <p>
        <strong>Fee Adjustment:</strong>
      </p>
    </div>
    <div class="col-sm-3">
      <p>:<%= @bid_number.bid_number %></p>
      <p>:<%= @bid_number.event_due_amount %> </p>
      <p>:<%= @bid_number.event_due_pay_status %> </p>
      <p>:<%= @bid_number.invoice_email_status %></p>
      <p>:<%= @bid_number.fee_adjustment %></p>
    </div>
  <div class="col-sm-6">
    <p><strong> Guests </strong></p>
    <% @guests = get_guests_with_bid_number(@bid_number.bid_number) %>
    <% @guests.each do |guest| %>
      <p><%= link_to guest.first_name + " " +guest.last_name  , [guest.event, guest] %></p>
    <% end %>
  </div>
  </div>
</div>
<ul class="nav nav-pills" role="tablist">
  <li role="presentation" class="active">
    <%= link_to 'Generate Invoice', new_bid_number_invoice_path(@bid_number), {:class => 'badge'}%> 
  </li>
</ul>
<div class="table-responsive">
 <table class="table table-striped">
  <tr>
    <th>Invoice Id</th>
    <th>Version</th>
    <th>Creation Date</th>
    <th>Email Status</th>
  </tr>

  <% invoices_list_sorted = @bid_number.invoices %>
  <% invoices_list_sorted.each do |invoice| %>
    <tr>
      <td><%= invoice.id %></td>
      <td><%= invoice.version %></td>
      <td><%= invoice.created_at %></td>
      <td><%= invoice.status %></td>
      <td><%= link_to 'Show' , [invoice.bid_number, invoice] %></td>
      <td><%= link_to 'Edit' , edit_bid_number_invoice_path(invoice.bid_number, invoice)%></td>
      <td><%= link_to 'Delete' , [invoice.bid_number, invoice] , method: :delete, data: {confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
</div>