config/routes.rb
Rails.application.routes.draw do
  get 'events/index'

  get 'event/index'

  get 'welcome/index'

  root 'welcome#index'

  resources :articles do
		resources :comments
	end

  resources :events do
    member do
      get 'upload_auctions'
      get 'upload_guests'
    end
    resources :auctions
    resources :guests
    resources :bid_numbers
  end

  resources :guests
  
  resources :auctions do
    resources :bids
  end

  resources :bid_numbers do
    resources :invoices 
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :auctions, :dependent => :destroy
	has_many :guests, :dependent => :destroy
	has_many :bid_numbers, :dependent => :destroy
end

app/controllers/events_controller.rb
require 'CSV'

class EventsController < ApplicationController
  
  def index
  	@events = Event.all
  end

  def new
	 @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def upload_auctions
    @event = Event.find(params[:id])

    filename = "/Users/shikhasu/Documents/roughWork/Auctions_test.csv"

    auction_rows = []
    CSV.foreach(filename, encoding:'iso-8859-1:utf-8',headers:true) do |row|
      auction_row = {}
      number = row['Number']
      name = row['Name']
      auction_row[:value] = row['Value']
      auction_row[:auction_name] = number + "_" + name

      puts auction_row[:auction_name] + ", " + auction_row[:value]
      if !auction_row[:auction_name].blank? && float_or_nil(auction_row[:value])
        auction_rows << auction_row
        puts auction_row.inspect
      end
    end

    Event.transaction do
      auction_rows.each do |auction_row|
        auction_new = @event.auctions.build(:name => auction_row[:auction_name], :description => auction_row[:auction_name], :status => :OPEN, :fair_market_value => auction_row[:value], :auction_type => :SILENT_AUCTION)
        auction_new.save
      end
    end

    redirect_to event_auctions_path(@event), notice: "Auctions uploaded for the event"
  end

  def upload_guests
    @event = Event.find(params[:id])
    filename = "/Users/shikhasu/Documents/roughWork/guest_test_upload.csv"

    guest_rows = []
    CSV.foreach(filename, encoding:'iso-8859-1:utf-8',headers:true) do |row|
      # Fields from excel
      guest_row = {}
      if !row['FIRST_NAME'].blank?
        puts "name " + row.inspect
      end
      guest_row[:first_name] = row['FIRST_NAME']
      guest_row[:last_name] = row['LAST_NAME']
      guest_row[:email] = row['EMAIL']
      guest_row[:guest_of] = row['GUEST_OF']
      guest_row[:dinner_tickets] = Integer_or_nil(row['DINNER_TICKETS'])
      guest_row[:registration_status] = row['PAY_STATUS']
      guest_row[:registration_fee] = float_or_nil(row['REGISTRATION_FEE'])
      guest_row[:registration_fee_mode] = row['PAYMENT_TYPE']
      guest_row[:billing_address_1] = row['ADDRESS']
      guest_row[:city] = row['CITY']
      guest_row[:zip_code] = Integer_or_nil(row['ZIP_CODE'])
      guest_row[:phone_number] = row['PHONE_NUMBER']
      guest_row[:table_number] = Integer_or_nil(row['TABLE_NUMBER'])

      if !guest_row[:first_name].blank? && !guest_row[:last_name].blank?  && !guest_row[:registration_status].blank?
        guest_rows << guest_row
        puts guest_row.inspect
      end
    end

    Guest.transaction do 
      guest_rows.each do |guest_row|
        guest_new = @event.guests.build(:first_name => guest_row[:first_name],  
                                         :last_name => guest_row[:last_name],
                                         :registration_status => guest_row[:registration_status],                                  
                                        :email => guest_row[:email], 
                                        :guest_of => guest_row[:guest_of],
                                        :dinner_tickets => guest_row[:dinner_tickets],
                                        :registration_fee => guest_row[:registration_fee],
                                        :registration_fee_mode => guest_row[:registration_fee_mode],
                                        :billing_address_1 => guest_row[:billing_address_1],
                                        :city => guest_row[:city],
                                        :zip_code => guest_row[:zip_code],
                                        :phone_number => guest_row[:phone_number],
                                        :table_number => guest_row[:table_number])
        save_result = guest_new.save
        puts guest_new.errors.inspect
      end
    end
    redirect_to event_guests_path(@event), notice: "Guests uploaded for the event"

  end

  def create
	@event = Event.new(event_params)
	
  	if @event.save
  		redirect_to @event
  	else
  		render 'new'
  	end
  end

  def update
    @event = Event.find(params[:id])
 
    if @event.update(event_params)
      redirect_to @event
    else
      render 'edit'
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path, notice: "Event is successfully deleted!"
  end

private
  def event_params
    params.require(:event).permit(:title, :description, :created_by)
  end
  
  def float_or_nil(string)
    if string.blank? 
      return nil 
    end
    Float(string.strip || '')
    rescue ArgumentError
    nil
  end
  def Integer_or_nil(string)
    if string.blank? 
      return nil 
    end
    Integer(string.strip || '')
    rescue ArgumentError
    nil
  end

end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for  @event ,:html => {:class => "form-horizontal center"} do |f|%>

	<% if @event && @event.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:
			</h2>
			<ul>
				<% @event.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="form-group">
			<%= f.label :title, class: "col-md-4 control-label"%>
			<div class="col-md-8">
			<%= f.text_field :title %>
			</div>
	</div>
	<div class="form-group">
		<%= f.label :description, class: "col-md-4 control-label"%>
		<div class="col-md-8">
		<%= f.text_area :description %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :created_by, class: "col-md-4 control-label"%>
		<div class="col-md-8">
		<%= f.text_field :created_by %>
		</div>
	</div>
	<div class="form-group">
		<div class="col-md-8">
			<%= f.submit "Submit", class: "btn btn-default btn-primary"%>
		</div>
	</div>

<% end %>

app/views/events/edit.html.erb
<div class="container-fluid">
	<%= render 'common/navbar' %>
</div>

<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="container-fluid">
	<%= render 'common/navbar' %>
</div>

<h1>Events</h1>

<ul class="nav nav-pills" role="tablist">
	<li role="presentation" class="active">
		<%= link_to 'New Event', new_event_path , {:class => 'badge'}%>
	</li>
</ul>

<div class="table-responsive">
 <table class="table table-striped">
	<tr>
		<th>Title</th>
		<th>Description</th>
		<th>Created By</th>
	</tr>
	<% @events.each do |event| %>
		<tr>
			<td><%= event.title %></td>
			<td><%= event.description %></td>
			<td><%= event.created_by %></td>
			<td><%= link_to 'Show' , event_path(event) %></td>
			<td><%= link_to 'Edit' , edit_event_path(event)%></td>
		</tr>
	<% end %>
</table>
<div>

app/views/events/new.html.erb
<div class="container-fluid">
	<%= render 'common/navbar' %>
</div>

<h1> Create a new Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<div class="container-fluid">
	<%= render 'common/navbar' %>
</div>

<%= link_to 'Back', events_path %>
<h1>Event</h1>
<div class="row">
	<div class="col-sm-6">
	  <ul class="list-group">
	    <li class="list-group-item"> <strong>Title : </strong> <%= @event.title %></li>
	    <li class="list-group-item"> <strong>Description : </strong> <%= @event.description %></li>
	    <li class="list-group-item"><%= link_to 'Auctions in the Event', (event_auctions_path(@event)) %></li>
	    <li class="list-group-item"><%= link_to 'Guests in the Event', (event_guests_path(@event)) %></li>
	    <li class="list-group-item"><%= link_to 'Bid Numbers in the Event', (event_bid_numbers_path(@event)) %></li>
	  </ul>
	</div><!-- /.col-sm-4 -->
</div>
<div class="row">
	<div class="col-sm-3">
		<ul class="nav nav-pills" role="tablist">
		<li role="presentation" class="active">
			<%= link_to 'Upload Auctions', upload_auctions_event_path(@event) ,{:class => 'badge'}%>
		</li>
		</ul>
	</div>
	<div class="col-sm-3">
		<ul class="nav nav-pills" role="tablist">
		<li role="presentation" class="active">
			<%= link_to 'Upload Guests', upload_guests_event_path(@event) ,{:class => 'badge'}%>
		</li>
		</ul>
	</div>
</div>
</div>